### ISSUE TITLE
Building on cygwin

### ISSUE THREAD

**Issue by Chronial** [nixprime/cpsm#10]
Building on cygwin works fine (with the cygwin setup.exe boost), but the output file has the wrong name. The generated python module file is called `cpsm_py.so`, but should be called `cpsm_py.dll`.

As a result, the matcher fails silently (just returns "0" as the only match). Renaming the file fixes the problem.

**Comment by nixprime** [comment]
I think this is due to an entirely unnecessary override in the CMake build file :/
