### ISSUE TITLE
denite support

### ISSUE THREAD

**Issue by Shougo** [nixprime/cpsm#28]
I have developed denite.nvim.
It is implemented as neovim remote plugin using Python3.

https://github.com/Shougo/denite.nvim

I want to add cpsm_matcher to optimize the speed.
But current cpsm only supports ctrlp and filter the list of string type.
I need the word of dictionary type support for denite.

**Comment by nixprime** [comment]
Sorry, I don't understand. Could you please clarify the signature of the function you want? i.e. what arguments you would pass to it, and what you'd expect it to return.

**Comment by Shougo** [comment]
Please correct me if I am wrong.

https://github.com/nixprime/cpsm/blob/master/autoload/cpsm.py#L31

cpsm has `ctrlp_match()` function.
It filters the string items of list.  It is ctrlp candidates format.

I need the filter function filters the dictionary items by 'word' key for denite.

**Comment by nixprime** [comment]
I've formally documented `cpsm_py.ctrlp_match` and added support for arbitrary iterators, so you can pass a generator that extracts the word key without needing to build an intermediate list:

```
$ python3
Python 3.5.2 (default, Jul  5 2016, 12:43:10) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cpsm_py
>>> print(cpsm_py.ctrlp_match.__doc__)
ctrlp_match(
    items, query, limit=-1, mmode=None, ispath=False, crfile=None,
    highlight_mode=None, match_crfile=False, max_threads=0,
    query_inverting_delimiter=None, unicode=False)

Returns a tuple `(results, regexes)` containing information about the items
in `items` that match `query`, in order of descending match quality.

Options:
limit -- if positive, the maximum number of results to return
mmode -- CtrlP match mode (default 'full-line', i.e. full path mode)
ispath -- if true, all items are paths
crfile -- if set, the currently open file
highlight_mode -- controls `regexes`, see README
match_crfile -- if false, never match `crfile`
max_threads -- if positive, limit on the number of matcher threads
query_inverting_delimiter -- see README
unicode -- if true, all items are UTF-8-encoded
>>> dict_items = []
>>> for word in "barfoo fbar foo/bar foo/fbar foo/foobar foo/foo_bar foo/foo_bar_test foo/foo_test_bar foo/FooBar foo/abar foo/qux foob/ar".split():
...     dict_items.append({"word": word})
... 
>>> cpsm_py.ctrlp_match((d["word"] for d in dict_items), "fb", ispath=True)
(['fbar', 'foo/fbar', 'foo/FooBar', 'foo/foo_bar', 'foo/foo_bar_test', 'foo/foo_test_bar', 'foo/bar', 'foo/foobar', 'foob/ar', 'foo/abar'], [])
```

Is this sufficient?

**Comment by Shougo** [comment]
Thank you!
No problem.  I will add cpsm matcher for denite.

**Comment by Shougo** [comment]
I have added cpsm support!
https://github.com/Shougo/denite.nvim/commit/04b5ef466e3e8789e827aaa0a09d9d195f4e2950

**Comment by nixprime** [comment]
Great! Let me know if you run into any issues.
