### ISSUE TITLE
[RFC] Boost is a heavy dependency (440MB)

### ISSUE THREAD

**Issue by kiryph** [nixprime/cpsm#30]
Installing a vim plugin should be an easy thing to do. Major external dependencies such as boost should be justified. 

A grep for `#include <boost/` shows following usage of boost libraries:
```
#include <boost/program_options.hpp>
#include <boost/utility/string_ref.hpp>
#include <boost/algorithm/cxx14/mismatch.hpp>
#include <boost/range/adaptor/reversed.hpp>
```

Are all of these really necessary?

E.g. IMHO parsing command line arguments are not a good enough reason for boost. They can be dealt in a different way, in particular, if only a few ones have to be parsed. Also consider this: the installation size of boost on my machine is about `440MB`.

The vim plugin `YouCompleteMe` has a frightening set of third-party dependencies including a few boost libraries. However, they have added the required boost libraries to the source tree:
https://github.com/Valloric/ycmd/tree/master/cpp/BoostParts
To use this plugin boost does not have to be installed separately.

I am quite sure any software development guide recommends KISS. Relying on boost typically is not.

What do you think? I know this project is most likely only a spare time project, however, if you like you could make it easier for others to use it as well (you have already published it on github).

**Comment by nixprime** [comment]
`boost::string_ref` is used extremely frequently and won't be obsolete until C++17 and `std::string_view` become ubiquitous, which won't be for a while. The rest are used rarely but have little additional cost given that `boost::string_ref` is non-negotiable.

> I am quite sure any software development guide recommends KISS. Relying on boost typically is not.

Reinventing a library as ubiquitous and widely-excepted as Boost is the opposite of KISS.

**Comment by kiryph** [comment]
What is your opinion about including the header file of `boost::string_ref` into your source tree?

Of course, reinventing would be a bad idea. However, that doesn't mean one has to use all different things out there. Even today people write programs in plain c with pointers. No std::string and other heavy things from stl.

Another reason could be:
boost::string_ref was introduced in 1.53 (February 4th, 2013) and someone is arguing on stackoverflow that it became mature with version 1.60 (December 17th, 2015) (http://stackoverflow.com/questions/16026467/how-to-compare-booststring-ref-to-stdstring). 
Not every platform provides the most reason version of boost libraries. Installing boost from source is also a task I would avoid expecting from someone to install a vim plugin.

I hope I didn't step on someone toes. This is definitely not my intention.
