### ISSUE TITLE
ERROR: function takes at most 11 arguments (12 given)

### ISSUE THREAD

**Issue by svenstaro** [nixprime/cpsm#33]
Using cpsm with the current git master of vim-ctrlp produces this error on pressing ctrlp: 

> ERROR: function takes at most 11 arguments (12 given)

**Comment by nixprime** [comment]
Re-run install.sh to rebuild the Python extension.

**Comment by svenstaro** [comment]
Oh dear. I should certainly have tried that first but the error didn't seem right! Thanks for the quick support.
