### ISSUE TITLE
Python version detection appears to be broken

### ISSUE THREAD

**Issue by LemonBoy** [nixprime/cpsm#35]
At least here on arch linux the usage of `PythonLibsCustom` over `PythonLibs` makes all the python3 builds to fail when loaded from within vim eg. by doing `:py3 import cpsm_py` with this stack trace
```
Traceback (most recent call last):                                                                                                                             
  File "<string>", line 1, in <module>
ImportError: ~/.vim/bundle/cpsm/autoload/cpsm_py.so: undefined symbol: forkpty
```
Moreover the linking phase happens instantly when using `PythonLibs` instead of taking the usual ~2 mins.

**Comment by svenstaro** [comment]
@LemonBoy same problem; I submitted a PR for this. Hopefully it gets merged.

**Comment by bulletmark** [comment]
Confirming that commit fixes the issue on Arch Linux. `install.sh` automatically determines default python3 and builds correctly.

**Comment by svenstaro** [comment]
Yup, good for me too.
