### ISSUE TITLE
Compilation fails on Mac OS X

### ISSUE THREAD

**Issue by zegervdv** [nixprime/cpsm#5]
When trying to compile using the `install.sh` script, it fails with following output:
https://gist.github.com/zegervdv/66ac5b35cc71dd8f0e68

I have installed boost via homebrew, am I still missing some dependency?
Mac OS X 10.10.3

**Comment by nixprime** [comment]
Can you pull and try again (after https://github.com/nixprime/cpsm/commit/97dac8ccfc241ccbd197e7ec3e3ed5571818f697)?

**Comment by zegervdv** [comment]
It still fails with the same error.

**Comment by nixprime** [comment]
I think you're suffering from the inverse of http://stackoverflow.com/questions/19912862/compiling-boostprogram-options-on-mac-os-x-with-g-4-8-mac-ports: your Boost libraries were compiled with GCC, but the compiler selected by CMake is Clang. How did you install Boost? Can you provide the output of `otool -L /usr/local/lib/libboost_program_options-mt.dylib`?

**Comment by zegervdv** [comment]
```
→ otool -L /usr/local/lib/libboost_program_options-mt.dylib
/usr/local/lib/libboost_program_options-mt.dylib:
	/usr/local/lib/libboost_program_options-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```

I've installed Boost with Homebrew from bottle. Maybe I should try to compile it?

**Comment by nixprime** [comment]
Actually, otool indicates that Boost was linked to libc++, which should only be the case for Clang... I wonder if you have another copy of Boost installed. Can you `cd ~/.vim/plugged/cpsm/build` and run `cmake -DBoost_DEBUG=ON ..`?

**Comment by zegervdv** [comment]
This is the output:
https://gist.github.com/zegervdv/c2c891b006a882ea2d5a

It searches for boost libraries in MATLAB first. I don't use MATLAB anymore, so I removed it, which solved the problem. 
Now I have the same issue as in #3.

Thank you for your help.
