### ISSUE TITLE
ERROR: function takes at most 8 arguments (10 given)

### ISSUE THREAD

**Issue by alex-tan** [nixprime/cpsm#6]
Hey discovered this plugin recently, very cool.

Just started getting this error after running `:PluginUpdate` this morning when activating CtrlP. Running OS X.

Commenting out
```vim
let g:ctrlp_match_func = {'match': 'cpsm#CtrlPMatch'}
```
fixes the issue.

**Comment by nixprime** [comment]
You need to re-run `install.sh` after updating to rebuild the Python extension.

**Comment by alex-tan** [comment]
That did it, thanks!
