### ISSUE TITLE
Extremely slow on cygwin

### ISSUE THREAD

**Issue by Chronial** [nixprime/cpsm#9]
I build the plugin on cygwin and it is just extremely slow (10-50 times slower that the default matcher). Any idea what might cause that?

**Comment by Chronial** [comment]
I think I found the culprit. It's a cygwin bug: https://cygwin.com/ml/cygwin/2012-08/msg00200.html
Setting `let g:cpsm_max_threads = 1` fixed the problem.

You might want to detect cygwin (`has("win32unix")`) and set this as default.

**Comment by nixprime** [comment]
Thanks for the report. Should be fixed in master shortly.
